giscus:
  enable: true
  repo: dgbjb20191230/dgbjb20191230.github.io
  repo_id: R_kgDOK9OOIA
  category: Announcements
  category_id: DIC_kwDOK9OOIM4Cb9tQ
  # Available values: pathname | url | title | og:title
  mapping: pathname
  # Available values: 0 | 1
  reactions_enabled: 1
   # Available values: 0 | 1
  emit_metadata: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: light
  # Available values: en | zh-CN
  lang: en
  # Place the comment box above the comments
  input_position: bottom
  # Load the comments lazily
  loading: lazy